### ISSUE TITLE
配置放在yml中就报错

### ISSUE THREAD

**Issue by hllinc** [zyf970617/mybatis-auto-create-table#1]

**Comment by zyf970617** [comment]
如果你想只用yml进行文件配置，那么你除了需要把这三个配置项移到yml文件外，还需要修改一个地方。 在MybatisTableConfig.java类中，通过注入PropertiesFactoryBean，将properties里的属性注入，如下

@Bean
public PropertiesFactoryBean configProperties() throws Exception{
    PropertiesFactoryBean propertiesFactoryBean = new PropertiesFactoryBean();
    PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
    propertiesFactoryBean.setLocations(resolver.getResources("classpath*:application.properties"));
    return propertiesFactoryBean;
}
如果你改成了只用yml，则需要修改如上配置文件，改成注入yml

**Comment by zyf970617** [comment]
我在配置里面已经说了哦，因为配置文件使用的是Properties形式的注入，所以是不会管yml里面的配置信息的，如果你想只用yml，那就需要换一种注入方式，把你在yml中的配置注入进去

**Comment by hllinc** [comment]
先分开吧。
